### ISSUE TITLE
Player appears twice in scoreboard

### ISSUE THREAD

**Issue by danielstocks** [doomdavve/squash-ladder#1]
URL: https://davve.net/squash/#2016-r4-d6

Chrome 52.0.2743.116 
Mac OS 10.10.5

Screenshot:
<img width="798" alt="screen shot 2016-08-25 at 15 42 29" src="https://cloud.githubusercontent.com/assets/52788/17967139/ad2a952e-6ada-11e6-9ddd-cd92fe3269d3.png">

**Comment by danielstocks** [comment]
Seems like the data coming from: https://davve.net/squash/load.cgi?division=2016-r4-d6 is corrupted

``` json
[
"440181de9f44a2be2e9ab5e64d562771283faa78",
"568e8510c824dee9ad76fb3449903ba204e14414",
"2016-07-07T08:03:10",
"212.116.72.179",
"{\"players\":[\"Mattias Anthyme Grah\",\"Fredrik Rosendahl\",\"Mattias Anthyme Grahn\",\"Erik Holm\",\"Mikael Neckman\",\"Hans Rothlin\",\"Petter Hallberger\"],\"games\":[[\"Erik Holm\",\"Petter Hallberger\",3,0,\"2016-06-01\",\"19:45\",\"6\"],[\"Fredrik Rosendahl\",\"Mattias Anthyme Grah\",0,0,\"2016-06-01\",\"19:45\",\"8\"],[\"Hans Rothlin\",\"Mikael Neckman\",1,3,\"2016-06-01\",\"19:45\",\"7\"],[\"Erik Holm\",\"Mattias Anthyme Grah\",1,3,\"2016-06-15\",\"19:45\",\"7\"],[\"Hans Rothlin\",\"Fredrik Rosendahl\",3,2,\"2016-06-15\",\"19:45\",\"8\"],[\"Mikael Neckman\",\"Petter Hallberger\",3,1,\"2016-06-15\",\"19:45\",\"6\"],[\"Erik Holm\",\"Hans Rothlin\",0,3,\"2016-06-22\",\"19:45\",\"8\"],[\"Mattias Anthyme Grahn\",\"Petter Hallberger\",3,2,\"2016-06-22\",\"19:45\",\"6\"],[\"Mikael Neckman\",\"Fredrik Rosendahl\",3,0,\"2016-06-22\",\"19:45\",\"7\"],[\"Fredrik Rosendahl\",\"Petter Hallberger\",2,3,\"2016-06-29\",\"19:45\",\"6\"],[\"Mattias Anthyme Grahn\",\"Hans Rothlin\",1,3,\"2016-06-29\",\"19:45\",\"7\"],[\"Mikael Neckman\",\"Erik Holm\",1,3,\"2016-06-29\",\"19:45\",\"8\"],[\"Fredrik Rosendahl\",\"Erik Holm\",1,3,\"2016-08-17\",\"19:45\",\"7\"],[\"Hans Rothlin\",\"Petter Hallberger\",0,0,\"2016-08-17\",\"19:45\",\"6\"],[\"Mattias Anthyme Grahn\",\"Mikael Neckman\",0,0,\"2016-08-17\",\"19:45\",\"8\"]],\"caption\":\"2016 round 4 division %d\"}"
]
```

**Comment by doomdavve** [comment]
Last character of his name is capped when put in the second column in the pdf document. This follows through the import and into the scoreboard as two different players.

**Comment by doomdavve** [comment]
I could fix it manually but a better import source would be the proper fix. Hi Daniel! Long time no see!

**Comment by danielstocks** [comment]
Hi!

I guess one solution is to improve the pdf scan, another could be to validate the data source being imported. For instance, only 6 players are allowed per division, so if there are more, you could easily spot duplicates?

Greetings from 🇹🇯

**Comment by doomdavve** [comment]
Sure, a warning for >6 players would be worthwhile. I'll try to remember to put that in, in case I have to do the pdf-import once more.

**Comment by doomdavve** [comment]
Manual edit complete.
